// This file is auto-generated by @hey-api/openapi-ts

export type ChatBase = {
    id: string;
    title: string;
    created_at: string;
    group_id: string;
};

export type RoleBase = {
    id: string;
    title: string;
    group_id: string;
    created_at: string;
    permissions: Array<RolePermissionsEnum>;
};

export type Body_auth_db_cookie_login_api_auth_jwt_login_post = {
    grant_type?: string | null;
    username: string;
    password: string;
    scope?: string;
    client_id?: string | null;
    client_secret?: string | null;
};

export type Body_reset_forgot_password_api_auth_forgot_password_post = {
    email: string;
};

export type Body_reset_reset_password_api_auth_reset_password_post = {
    token: string;
    password: string;
};

export type Body_upload_avatar_api_groups_avatar__group_id__post = {
    image: (Blob | File);
};

export type Body_upload_avatar_api_users_avatar_me_post = {
    image: (Blob | File);
};

export type Body_upload_panorama_api_groups_panorama__group_id__post = {
    image: (Blob | File);
};

export type Body_verify_request_token_api_auth_request_verify_token_post = {
    email: string;
};

export type Body_verify_verify_api_auth_verify_post = {
    token: string;
};

export type ChatCreate = {
    title: string;
    group_id?: string | null;
};

export type GroupCreate = {
    title: string;
    description: string;
};

export type RoleCreate = {
    title: string;
    group_id: string;
    permissions?: Array<RolePermissionsEnum>;
};

export type ErrorModel = {
    detail: string | {
    [key: string]: (string);
};
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ChatRead = {
    id: string;
    title: string;
    created_at: string;
    group_id: string;
};

export type GroupRead = {
    id: string;
    title: string;
    description: string;
    avatar_path?: string | null;
    panorama_path?: string | null;
    created_at: string;
    chats?: Array<ChatBase>;
    roles?: Array<RoleBase>;
};

export type MessagePaginatedRead = {
    messages: Array<MessageRead>;
    page: number;
    next_page: number;
};

export type MessageRead = {
    id: string;
    id_in_chat: number;
    /**
     * Message must be less than 2000 characters
     */
    message: string;
    user_id: string;
    to_chat_id: string;
    created_at: string;
    author?: string | null;
};

export type RoleRead = {
    id: string;
    title: string;
    group_id: string;
    created_at: string;
    permissions: Array<RolePermissionsEnum>;
};

export type RolePermissionsEnum = 'can_all' | 'can_edit_group_settings' | 'can_edit_roles' | 'can_control_chats' | 'can_send_message' | 'can_invite';

export type ChatUpdate = {
    title?: string | null;
};

export type GroupUpdate = {
    title?: string | null;
    description?: string | null;
    avatar_path?: string | null;
    panorama_path?: string | null;
};

export type RoleUpdate = {
    title?: string | null;
    permissions?: Array<RolePermissionsEnum> | null;
};

export type UserCreate = {
    name: string;
    account_name: string;
    email: string;
    password: string;
    is_active?: boolean | null;
    is_superuser?: boolean | null;
    is_verified?: boolean | null;
};

export type UserRead = {
    id: string;
    name: string;
    account_name: string;
    created_at: string;
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    is_verified?: boolean;
};

export type UserUpdate = {
    name?: string | null;
    avatar_path?: string | null;
    password?: string | null;
    email?: string | null;
    is_active?: boolean | null;
    is_superuser?: boolean | null;
    is_verified?: boolean | null;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type PostApiAuthJwtLoginData = {
    formData: Body_auth_db_cookie_login_api_auth_jwt_login_post;
};

export type PostApiAuthJwtLoginResponse = unknown | void;

export type PostApiAuthJwtLogoutResponse = unknown | void;

export type PostApiAuthRegisterData = {
    requestBody: UserCreate;
};

export type PostApiAuthRegisterResponse = UserRead;

export type PostApiAuthForgotPasswordData = {
    requestBody: Body_reset_forgot_password_api_auth_forgot_password_post;
};

export type PostApiAuthForgotPasswordResponse = unknown;

export type PostApiAuthResetPasswordData = {
    requestBody: Body_reset_reset_password_api_auth_reset_password_post;
};

export type PostApiAuthResetPasswordResponse = unknown;

export type PostApiAuthRequestVerifyTokenData = {
    requestBody: Body_verify_request_token_api_auth_request_verify_token_post;
};

export type PostApiAuthRequestVerifyTokenResponse = unknown;

export type PostApiAuthVerifyData = {
    requestBody: Body_verify_verify_api_auth_verify_post;
};

export type PostApiAuthVerifyResponse = UserRead;

export type GetApiAuthMeResponse = unknown;

export type GetApiAuthMeAlterntiveResponse = unknown;

export type PostApiAuthAccessTokenResponse = unknown;

export type GetApiUsersMeResponse = UserRead;

export type PatchApiUsersMeData = {
    requestBody: UserUpdate;
};

export type PatchApiUsersMeResponse = UserRead;

export type GetApiUsersByIdData = {
    id: string;
};

export type GetApiUsersByIdResponse = UserRead;

export type PatchApiUsersByIdData = {
    id: string;
    requestBody: UserUpdate;
};

export type PatchApiUsersByIdResponse = UserRead;

export type DeleteApiUsersByIdData = {
    id: string;
};

export type DeleteApiUsersByIdResponse = void;

export type GetApiUsersAvatarMeResponse = unknown;

export type PostApiUsersAvatarMeData = {
    formData: Body_upload_avatar_api_users_avatar_me_post;
};

export type PostApiUsersAvatarMeResponse = unknown;

export type GetApiGroupsUserGroupsMeResponse = Array<GroupRead>;

export type GetApiGroupsAvatarByGroupIdData = {
    groupId: string;
};

export type GetApiGroupsAvatarByGroupIdResponse = unknown;

export type PostApiGroupsAvatarByGroupIdData = {
    formData: Body_upload_avatar_api_groups_avatar__group_id__post;
    groupId: string;
};

export type PostApiGroupsAvatarByGroupIdResponse = unknown;

export type GetApiGroupsPanoramaByGroupIdData = {
    groupId: string;
};

export type GetApiGroupsPanoramaByGroupIdResponse = unknown;

export type PostApiGroupsPanoramaByGroupIdData = {
    formData: Body_upload_panorama_api_groups_panorama__group_id__post;
    groupId: string;
};

export type PostApiGroupsPanoramaByGroupIdResponse = unknown;

export type GetApiGroupsInviteByGroupIdData = {
    groupId: string;
};

export type GetApiGroupsInviteByGroupIdResponse = unknown;

export type PostApiGroupsInviteData = {
    requestBody: string;
};

export type PostApiGroupsInviteResponse = unknown;

export type PostApiGroupsLeaveByGroupIdData = {
    groupId: string;
};

export type PostApiGroupsLeaveByGroupIdResponse = unknown;

export type PatchApiGroupsTitleByGroupIdData = {
    groupId: string;
    requestBody: string;
};

export type PatchApiGroupsTitleByGroupIdResponse = GroupRead;

export type GetApiGroupsByGroupIdData = {
    groupId: string;
};

export type GetApiGroupsByGroupIdResponse = GroupRead;

export type PatchApiGroupsByGroupIdData = {
    groupId: string;
    requestBody: GroupUpdate;
};

export type PatchApiGroupsByGroupIdResponse = GroupRead;

export type DeleteApiGroupsByGroupIdData = {
    groupId: string;
};

export type DeleteApiGroupsByGroupIdResponse = unknown;

export type PostApiGroupsData = {
    requestBody: GroupCreate;
};

export type PostApiGroupsResponse = GroupRead;

export type GetApiChatsGroupChatsByGroupIdData = {
    groupId: string;
};

export type GetApiChatsGroupChatsByGroupIdResponse = Array<ChatRead>;

export type PostApiChatsByGroupIdData = {
    groupId: string;
    requestBody: ChatCreate;
};

export type PostApiChatsByGroupIdResponse = unknown;

export type PatchApiChatsByChatIdData = {
    chatId: string;
    requestBody: ChatUpdate;
};

export type PatchApiChatsByChatIdResponse = unknown;

export type DeleteApiChatsByChatIdData = {
    chatId: string;
};

export type DeleteApiChatsByChatIdResponse = unknown;

export type GetApiRolesGroupByRoleIdData = {
    roleId: string;
};

export type GetApiRolesGroupByRoleIdResponse = RoleRead;

export type DeleteApiRolesGroupByRoleIdData = {
    roleId: string;
};

export type DeleteApiRolesGroupByRoleIdResponse = unknown;

export type GetApiRolesGroupPermissionsMeByGroupIdData = {
    groupId: string;
};

export type GetApiRolesGroupPermissionsMeByGroupIdResponse = unknown;

export type PostApiRolesGroupByGroupIdData = {
    groupId: string;
    requestBody: RoleCreate;
};

export type PostApiRolesGroupByGroupIdResponse = RoleRead;

export type PatchApiRolesGroupByGroupIdByRoleIdData = {
    groupId: string;
    requestBody: RoleUpdate;
    roleId: string;
};

export type PatchApiRolesGroupByGroupIdByRoleIdResponse = unknown;

export type GetApiMessagesChatByChatIdData = {
    amount?: number;
    chatId: string;
    /**
     * Page mean how many messages skip it equal amount * (page - 1)
     */
    page?: number;
};

export type GetApiMessagesChatByChatIdResponse = MessagePaginatedRead;

export type GetApiResponse = unknown;

export type $OpenApiTs = {
    '/api/auth/jwt/login': {
        post: {
            req: PostApiAuthJwtLoginData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * No Content
                 */
                204: void;
                /**
                 * Bad Request
                 */
                400: ErrorModel;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/auth/jwt/logout': {
        post: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * No Content
                 */
                204: void;
                /**
                 * Missing token or inactive user.
                 */
                401: unknown;
            };
        };
    };
    '/api/auth/register': {
        post: {
            req: PostApiAuthRegisterData;
            res: {
                /**
                 * Successful Response
                 */
                201: UserRead;
                /**
                 * Bad Request
                 */
                400: ErrorModel;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/auth/forgot-password': {
        post: {
            req: PostApiAuthForgotPasswordData;
            res: {
                /**
                 * Successful Response
                 */
                202: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/auth/reset-password': {
        post: {
            req: PostApiAuthResetPasswordData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Bad Request
                 */
                400: ErrorModel;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/auth/request-verify-token': {
        post: {
            req: PostApiAuthRequestVerifyTokenData;
            res: {
                /**
                 * Successful Response
                 */
                202: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/auth/verify': {
        post: {
            req: PostApiAuthVerifyData;
            res: {
                /**
                 * Successful Response
                 */
                200: UserRead;
                /**
                 * Bad Request
                 */
                400: ErrorModel;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/auth/me': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
    };
    '/api/auth/me_alterntive': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
    };
    '/api/auth/access_token': {
        post: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
    };
    '/api/users/me': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: UserRead;
                /**
                 * Missing token or inactive user.
                 */
                401: unknown;
            };
        };
        patch: {
            req: PatchApiUsersMeData;
            res: {
                /**
                 * Successful Response
                 */
                200: UserRead;
                /**
                 * Bad Request
                 */
                400: ErrorModel;
                /**
                 * Missing token or inactive user.
                 */
                401: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/users/{id}': {
        get: {
            req: GetApiUsersByIdData;
            res: {
                /**
                 * Successful Response
                 */
                200: UserRead;
                /**
                 * Missing token or inactive user.
                 */
                401: unknown;
                /**
                 * Not a superuser.
                 */
                403: unknown;
                /**
                 * The user does not exist.
                 */
                404: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        patch: {
            req: PatchApiUsersByIdData;
            res: {
                /**
                 * Successful Response
                 */
                200: UserRead;
                /**
                 * Bad Request
                 */
                400: ErrorModel;
                /**
                 * Missing token or inactive user.
                 */
                401: unknown;
                /**
                 * Not a superuser.
                 */
                403: unknown;
                /**
                 * The user does not exist.
                 */
                404: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        delete: {
            req: DeleteApiUsersByIdData;
            res: {
                /**
                 * Successful Response
                 */
                204: void;
                /**
                 * Missing token or inactive user.
                 */
                401: unknown;
                /**
                 * Not a superuser.
                 */
                403: unknown;
                /**
                 * The user does not exist.
                 */
                404: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/users/avatar/me': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
        post: {
            req: PostApiUsersAvatarMeData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/groups/user_groups/me': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: Array<GroupRead>;
            };
        };
    };
    '/api/groups/avatar/{group_id}': {
        get: {
            req: GetApiGroupsAvatarByGroupIdData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        post: {
            req: PostApiGroupsAvatarByGroupIdData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/groups/panorama/{group_id}': {
        get: {
            req: GetApiGroupsPanoramaByGroupIdData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        post: {
            req: PostApiGroupsPanoramaByGroupIdData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/groups/invite/{group_id}': {
        get: {
            req: GetApiGroupsInviteByGroupIdData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/groups/invite': {
        post: {
            req: PostApiGroupsInviteData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/groups/leave/{group_id}': {
        post: {
            req: PostApiGroupsLeaveByGroupIdData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/groups/title/{group_id}': {
        patch: {
            req: PatchApiGroupsTitleByGroupIdData;
            res: {
                /**
                 * Successful Response
                 */
                200: GroupRead;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/groups/{group_id}': {
        get: {
            req: GetApiGroupsByGroupIdData;
            res: {
                /**
                 * Successful Response
                 */
                200: GroupRead;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        patch: {
            req: PatchApiGroupsByGroupIdData;
            res: {
                /**
                 * Successful Response
                 */
                200: GroupRead;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        delete: {
            req: DeleteApiGroupsByGroupIdData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/groups/': {
        post: {
            req: PostApiGroupsData;
            res: {
                /**
                 * Successful Response
                 */
                200: GroupRead;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/chats/group_chats/{group_id}': {
        get: {
            req: GetApiChatsGroupChatsByGroupIdData;
            res: {
                /**
                 * Successful Response
                 */
                200: Array<ChatRead>;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/chats/{group_id}': {
        post: {
            req: PostApiChatsByGroupIdData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/chats/{chat_id}': {
        patch: {
            req: PatchApiChatsByChatIdData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        delete: {
            req: DeleteApiChatsByChatIdData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/roles_group/{role_id}': {
        get: {
            req: GetApiRolesGroupByRoleIdData;
            res: {
                /**
                 * Successful Response
                 */
                200: RoleRead;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        delete: {
            req: DeleteApiRolesGroupByRoleIdData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/roles_group/permissions/me/{group_id}': {
        get: {
            req: GetApiRolesGroupPermissionsMeByGroupIdData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/roles_group/{group_id}': {
        post: {
            req: PostApiRolesGroupByGroupIdData;
            res: {
                /**
                 * Successful Response
                 */
                200: RoleRead;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/roles_group/{group_id}/{role_id}': {
        patch: {
            req: PatchApiRolesGroupByGroupIdByRoleIdData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/messages/chat/{chat_id}': {
        get: {
            req: GetApiMessagesChatByChatIdData;
            res: {
                /**
                 * Successful Response
                 */
                200: MessagePaginatedRead;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
    };
};