import { deleteGroupApiGroupsGroupIdDeleteMutation, getGroupApiGroupsGroupIdGetOptions, getGroupMembersCountApiGroupsGroupIdMembersCountGetOptions, getMyGroupApiGroupsMeGroupsGetOptions, getMyGroupsWithLastMessageApiGroupsMeWithLastMessageGetOptions, leaveGroupApiGroupsLeaveGroupIdPostMutation } from '@/shared/api/generated/@tanstack/react-query.gen'

export const autoGroupQueryProps = {
  delete: deleteGroupApiGroupsGroupIdDeleteMutation,
  get: getGroupApiGroupsGroupIdGetOptions,
  getMembersCount: getGroupMembersCountApiGroupsGroupIdMembersCountGetOptions,
  getMyGroups: getMyGroupApiGroupsMeGroupsGetOptions,
  getMyGroupsWithLastMessage: getMyGroupsWithLastMessageApiGroupsMeWithLastMessageGetOptions,
  leave: leaveGroupApiGroupsLeaveGroupIdPostMutation,
}
