/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GroupsIndexRouteImport } from './routes/groups/index'
import { Route as GroupsCreateSimpleRouteImport } from './routes/groups/createSimple'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo.tanstack-query'
import { Route as VerifyEmailChar123TokenChar125RouteImport } from './routes/verify.$email.{-$token}'
import { Route as GroupGroupTypeChar123GroupIdChar125RouteImport } from './routes/group/$groupType/{-$groupId}'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsCreateSimpleRoute = GroupsCreateSimpleRouteImport.update({
  id: '/groups/createSimple',
  path: '/groups/createSimple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailChar123TokenChar125Route =
  VerifyEmailChar123TokenChar125RouteImport.update({
    id: '/verify/$email/{-$token}',
    path: '/verify/$email/{-$token}',
    getParentRoute: () => rootRouteImport,
  } as any)
const GroupGroupTypeChar123GroupIdChar125Route =
  GroupGroupTypeChar123GroupIdChar125RouteImport.update({
    id: '/group/$groupType/{-$groupId}',
    path: '/group/$groupType/{-$groupId}',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/registration': typeof RegistrationRoute
  '/search': typeof SearchRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/groups/createSimple': typeof GroupsCreateSimpleRoute
  '/groups': typeof GroupsIndexRoute
  '/group/$groupType/{-$groupId}': typeof GroupGroupTypeChar123GroupIdChar125Route
  '/verify/$email/{-$token}': typeof VerifyEmailChar123TokenChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/registration': typeof RegistrationRoute
  '/search': typeof SearchRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/groups/createSimple': typeof GroupsCreateSimpleRoute
  '/groups': typeof GroupsIndexRoute
  '/group/$groupType/{-$groupId}': typeof GroupGroupTypeChar123GroupIdChar125Route
  '/verify/$email/{-$token}': typeof VerifyEmailChar123TokenChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/registration': typeof RegistrationRoute
  '/search': typeof SearchRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/groups/createSimple': typeof GroupsCreateSimpleRoute
  '/groups/': typeof GroupsIndexRoute
  '/group/$groupType/{-$groupId}': typeof GroupGroupTypeChar123GroupIdChar125Route
  '/verify/$email/{-$token}': typeof VerifyEmailChar123TokenChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/registration'
    | '/search'
    | '/demo/tanstack-query'
    | '/groups/createSimple'
    | '/groups'
    | '/group/$groupType/{-$groupId}'
    | '/verify/$email/{-$token}'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/registration'
    | '/search'
    | '/demo/tanstack-query'
    | '/groups/createSimple'
    | '/groups'
    | '/group/$groupType/{-$groupId}'
    | '/verify/$email/{-$token}'
  id:
    | '__root__'
    | '/'
    | '/registration'
    | '/search'
    | '/demo/tanstack-query'
    | '/groups/createSimple'
    | '/groups/'
    | '/group/$groupType/{-$groupId}'
    | '/verify/$email/{-$token}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegistrationRoute: typeof RegistrationRoute
  SearchRoute: typeof SearchRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  GroupsCreateSimpleRoute: typeof GroupsCreateSimpleRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  GroupGroupTypeChar123GroupIdChar125Route: typeof GroupGroupTypeChar123GroupIdChar125Route
  VerifyEmailChar123TokenChar125Route: typeof VerifyEmailChar123TokenChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/createSimple': {
      id: '/groups/createSimple'
      path: '/groups/createSimple'
      fullPath: '/groups/createSimple'
      preLoaderRoute: typeof GroupsCreateSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$email/{-$token}': {
      id: '/verify/$email/{-$token}'
      path: '/verify/$email/{-$token}'
      fullPath: '/verify/$email/{-$token}'
      preLoaderRoute: typeof VerifyEmailChar123TokenChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/$groupType/{-$groupId}': {
      id: '/group/$groupType/{-$groupId}'
      path: '/group/$groupType/{-$groupId}'
      fullPath: '/group/$groupType/{-$groupId}'
      preLoaderRoute: typeof GroupGroupTypeChar123GroupIdChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegistrationRoute: RegistrationRoute,
  SearchRoute: SearchRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  GroupsCreateSimpleRoute: GroupsCreateSimpleRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  GroupGroupTypeChar123GroupIdChar125Route:
    GroupGroupTypeChar123GroupIdChar125Route,
  VerifyEmailChar123TokenChar125Route: VerifyEmailChar123TokenChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
