"""empty message

Revision ID: 6931c02fe05c
Revises: a262353bcdb6
Create Date: 2025-03-28 00:40:12.851056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6931c02fe05c'
down_revision: Union[str, None] = 'a262353bcdb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_to_group', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('user_to_group', 'group_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('user_to_group', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('user_to_personal_chat', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('user_to_personal_chat', 'personal_chat_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('user_to_personal_chat', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_to_personal_chat', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('user_to_personal_chat', 'personal_chat_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('user_to_personal_chat', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('user_to_group', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('user_to_group', 'group_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('user_to_group', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
