"""empty message

Revision ID: a262353bcdb6
Revises: 85c4602febe5
Create Date: 2025-03-27 20:25:09.020798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a262353bcdb6'
down_revision: Union[str, None] = '85c4602febe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_group', sa.Column('title', sa.String(), nullable=False))
    op.add_column('user', sa.Column('name', sa.String(), nullable=False))
    op.add_column('user', sa.Column('account_name', sa.String(), nullable=False))
    op.add_column('user', sa.Column('avatar_path', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['account_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'avatar_path')
    op.drop_column('user', 'account_name')
    op.drop_column('user', 'name')
    op.drop_column('role_group', 'title')
    # ### end Alembic commands ###
