"""first revision

Revision ID: 59099839bd04
Revises: 0ec37b8fa77c
Create Date: 2025-08-30 18:51:59.858530

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "59099839bd04"
down_revision: Union[str, None] = "0ec37b8fa77c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_chat_user", "user_to_group", ["group_id", "user_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_chat_user", "user_to_group", type_="unique")
    # ### end Alembic commands ###
