"""empty message

Revision ID: ad38c01ae14b
Revises: 59099839bd04
Create Date: 2025-11-25 23:57:46.041621

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ad38c01ae14b"
down_revision: Union[str, None] = "59099839bd04"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("simple_group", sa.Column("is_public", sa.Boolean(), nullable=False))
    op.drop_constraint(op.f("uq_chat_user"), "user_to_group", type_="unique")
    op.create_unique_constraint(
        "uq_group_user", "user_to_group", ["group_id", "user_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_group_user", "user_to_group", type_="unique")
    op.create_unique_constraint(
        op.f("uq_chat_user"),
        "user_to_group",
        ["group_id", "user_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("simple_group", "is_public")
    # ### end Alembic commands ###
