"""empty message

Revision ID: f5793650043b
Revises: 52eae9c9c4e7
Create Date: 2025-08-17 00:36:18.266189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5793650043b'
down_revision: Union[str, None] = '52eae9c9c4e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_token', sa.Column('expired_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('refresh_token', 'expires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_token', sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('refresh_token', 'expired_at')
    # ### end Alembic commands ###
