"""empty message

Revision ID: 52eae9c9c4e7
Revises: 0a81e25e3b44
Create Date: 2025-08-17 00:17:30.119106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52eae9c9c4e7'
down_revision: Union[str, None] = '0a81e25e3b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('role_group_id_fkey', 'role', type_='foreignkey')
    op.drop_column('role', 'group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('group_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('role_group_id_fkey', 'role', 'group', ['group_id'], ['id'])
    # ### end Alembic commands ###
