"""empty message

Revision ID: 9a8a067a6785
Revises: 12473a34db89
Create Date: 2025-08-20 22:11:00.722231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a8a067a6785'
down_revision: Union[str, None] = '12473a34db89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_group',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_to_usergroup',
    sa.Column('user_group_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_group_id'], ['user_to_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('group', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('role_user_group_id_fkey', 'role', type_='foreignkey')
    op.drop_column('role', 'user_group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('user_group_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('role_user_group_id_fkey', 'role', 'user_to_group', ['user_group_id'], ['id'])
    op.alter_column('group', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('role_to_usergroup')
    op.drop_table('personal_group')
    # ### end Alembic commands ###
