"""empty message

Revision ID: 64f5ece52f0f
Revises: e0b525ab09b1
Create Date: 2025-06-01 22:37:41.365641

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "64f5ece52f0f"
down_revision: Union[str, None] = "e0b525ab09b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
