// This file is auto-generated by @hey-api/openapi-ts

export const $BaseChatSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        group_id: {
            type: 'string',
            format: 'uuid',
            title: 'Group Id'
        }
    },
    type: 'object',
    required: ['id', 'title', 'created_at', 'group_id'],
    title: 'BaseChatSchema'
} as const;

export const $BaseRoleGroupSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        permissions: {
            items: {
                '$ref': '#/components/schemas/RolePermissionsEnum'
            },
            type: 'array',
            title: 'Permissions'
        },
        group_id: {
            type: 'string',
            format: 'uuid',
            title: 'Group Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'title', 'permissions', 'group_id', 'created_at'],
    title: 'BaseRoleGroupSchema'
} as const;

export const $Body_auth_db_cookie_login_api_auth_jwt_login_post = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_auth_db_cookie_login_api_auth_jwt_login_post'
} as const;

export const $Body_reset_forgot_password_api_auth_forgot_password_post = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        }
    },
    type: 'object',
    required: ['email'],
    title: 'Body_reset_forgot_password_api_auth_forgot_password_post'
} as const;

export const $Body_reset_reset_password_api_auth_reset_password_post = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        password: {
            type: 'string',
            title: 'Password'
        }
    },
    type: 'object',
    required: ['token', 'password'],
    title: 'Body_reset_reset_password_api_auth_reset_password_post'
} as const;

export const $Body_upload_avatar_api_groups_avatar__group_uuid__post = {
    properties: {
        image: {
            type: 'string',
            format: 'binary',
            title: 'Image'
        }
    },
    type: 'object',
    required: ['image'],
    title: 'Body_upload_avatar_api_groups_avatar__group_uuid__post'
} as const;

export const $Body_upload_avatar_api_users_avatar__group_uuid__post = {
    properties: {
        image: {
            type: 'string',
            format: 'binary',
            title: 'Image'
        }
    },
    type: 'object',
    required: ['image'],
    title: 'Body_upload_avatar_api_users_avatar__group_uuid__post'
} as const;

export const $Body_upload_panorama_api_groups_panorama__group_uuid__post = {
    properties: {
        image: {
            type: 'string',
            format: 'binary',
            title: 'Image'
        }
    },
    type: 'object',
    required: ['image'],
    title: 'Body_upload_panorama_api_groups_panorama__group_uuid__post'
} as const;

export const $Body_verify_request_token_api_auth_request_verify_token_post = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        }
    },
    type: 'object',
    required: ['email'],
    title: 'Body_verify_request_token_api_auth_request_verify_token_post'
} as const;

export const $Body_verify_verify_api_auth_verify_post = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        }
    },
    type: 'object',
    required: ['token'],
    title: 'Body_verify_verify_api_auth_verify_post'
} as const;

export const $CreateChatSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'CreateChatSchema'
} as const;

export const $CreateGroupSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title', 'description'],
    title: 'CreateGroupSchema'
} as const;

export const $CreateMessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        },
        user_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'User Id'
        },
        to_chat_id: {
            type: 'string',
            format: 'uuid',
            title: 'To Chat Id'
        },
        is_group: {
            type: 'boolean',
            title: 'Is Group'
        }
    },
    type: 'object',
    required: ['message', 'to_chat_id', 'is_group'],
    title: 'CreateMessageSchema'
} as const;

export const $CreatePersonalChatSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'CreatePersonalChatSchema'
} as const;

export const $CreateRoleGroupSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        group_id: {
            type: 'string',
            format: 'uuid',
            title: 'Group Id'
        }
    },
    type: 'object',
    required: ['title', 'group_id'],
    title: 'CreateRoleGroupSchema'
} as const;

export const $ErrorModel = {
    properties: {
        detail: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    additionalProperties: {
                        type: 'string'
                    },
                    type: 'object'
                }
            ],
            title: 'Detail'
        }
    },
    type: 'object',
    required: ['detail'],
    title: 'ErrorModel'
} as const;

export const $HTTPValidationError = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const $ReadChatSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        group_id: {
            type: 'string',
            format: 'uuid',
            title: 'Group Id'
        }
    },
    type: 'object',
    required: ['id', 'title', 'created_at', 'group_id'],
    title: 'ReadChatSchema'
} as const;

export const $ReadGroupSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        avatar_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatar Path'
        },
        panorama_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Panorama Path'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        chats: {
            items: {
                '$ref': '#/components/schemas/BaseChatSchema'
            },
            type: 'array',
            title: 'Chats',
            default: []
        },
        roles: {
            items: {
                '$ref': '#/components/schemas/BaseRoleGroupSchema'
            },
            type: 'array',
            title: 'Roles',
            default: []
        }
    },
    type: 'object',
    required: ['id', 'title', 'description', 'avatar_path', 'panorama_path', 'created_at'],
    title: 'ReadGroupSchema'
} as const;

export const $ReadMessageSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        id_in_chat: {
            type: 'integer',
            title: 'Id In Chat'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        to_chat_id: {
            type: 'string',
            format: 'uuid',
            title: 'To Chat Id'
        },
        is_group: {
            type: 'boolean',
            title: 'Is Group'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        author: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Author'
        }
    },
    type: 'object',
    required: ['id', 'id_in_chat', 'message', 'user_id', 'to_chat_id', 'is_group', 'created_at'],
    title: 'ReadMessageSchema'
} as const;

export const $ReadPersonalChatSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'title', 'created_at'],
    title: 'ReadPersonalChatSchema'
} as const;

export const $ReadRoleGroupSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        permissions: {
            items: {
                '$ref': '#/components/schemas/RolePermissionsEnum'
            },
            type: 'array',
            title: 'Permissions'
        },
        group_id: {
            type: 'string',
            format: 'uuid',
            title: 'Group Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'title', 'permissions', 'group_id', 'created_at'],
    title: 'ReadRoleGroupSchema'
} as const;

export const $RolePermissionsEnum = {
    type: 'string',
    enum: ['can_all', 'can_edit_roles', 'can_set_avatar', 'can_set_panorama', 'can_control_chats', 'can_send_message'],
    title: 'RolePermissionsEnum'
} as const;

export const $UpdateChatSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        }
    },
    type: 'object',
    title: 'UpdateChatSchema'
} as const;

export const $UpdateGroupSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'UpdateGroupSchema'
} as const;

export const $UpdateMessageSchema = {
    properties: {
        message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'UpdateMessageSchema'
} as const;

export const $UpdatePersonalChatSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        }
    },
    type: 'object',
    title: 'UpdatePersonalChatSchema'
} as const;

export const $UpdateRoleGroupSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        }
    },
    type: 'object',
    title: 'UpdateRoleGroupSchema'
} as const;

export const $UserCreate = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        account_name: {
            type: 'string',
            title: 'Account Name'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Superuser',
            default: false
        },
        is_verified: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['name', 'account_name', 'email', 'password'],
    title: 'UserCreate'
} as const;

export const $UserRead = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        account_name: {
            type: 'string',
            title: 'Account Name'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['id', 'name', 'account_name', 'created_at', 'email'],
    title: 'UserRead'
} as const;

export const $UserUpdate = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        is_superuser: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Superuser'
        },
        is_verified: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Verified'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'UserUpdate'
} as const;

export const $ValidationError = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;