// This file is auto-generated by @hey-api/openapi-ts

export type BaseChatSchema = {
    id: string;
    title: string;
    created_at: string;
    group_id: string;
};

export type BaseRoleGroupSchema = {
    id: number;
    title: string;
    permissions: Array<RolePermissionsEnum>;
    group_id: string;
    created_at: string;
};

export type BearerResponse = {
    access_token: string;
    token_type: string;
};

export type Body_auth_jwt_login_api_auth_jwt_login_post = {
    grant_type?: string | null;
    username: string;
    password: string;
    scope?: string;
    client_id?: string | null;
    client_secret?: string | null;
};

export type Body_reset_forgot_password_api_auth_forgot_password_post = {
    email: string;
};

export type Body_reset_reset_password_api_auth_reset_password_post = {
    token: string;
    password: string;
};

export type Body_upload_avatar_api_groups_avatar__group_uuid__post = {
    image: (Blob | File);
};

export type Body_upload_avatar_api_users_avatar__group_uuid__post = {
    image: (Blob | File);
};

export type Body_upload_panorama_api_groups_panorama__group_uuid__post = {
    image: (Blob | File);
};

export type Body_verify_request_token_api_auth_request_verify_token_post = {
    email: string;
};

export type Body_verify_verify_api_auth_verify_post = {
    token: string;
};

export type CreateChatSchema = {
    title: string;
    group_id: string;
};

export type CreateGroupSchema = {
    title: string;
};

export type CreatePersonalChatSchema = {
    title: string;
};

export type CreateRoleGroupSchema = {
    title: string;
};

export type ErrorModel = {
    detail: string | {
    [key: string]: (string);
};
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ReadChatSchema = {
    id: string;
    title: string;
    created_at: string;
    group_id: string;
};

export type ReadGroupSchema = {
    id: string;
    title: string;
    avatar_path: string | null;
    panorama_path: string | null;
    created_at: string;
    chats?: Array<BaseChatSchema>;
    roles?: Array<BaseRoleGroupSchema>;
};

export type ReadPersonalChatSchema = {
    id: string;
    title: string;
    created_at: string;
};

export type ReadRoleGroupSchema = {
    id: number;
    title: string;
    permissions: Array<RolePermissionsEnum>;
    group_id: string;
    created_at: string;
};

export type RolePermissionsEnum = 'can_all' | 'can_edit_roles' | 'can_set_avatar' | 'can_set_panorama' | 'can_control_chats' | 'can_send_message';

export type UpdateChatSchema = {
    title?: string | null;
    group_id?: string | null;
};

export type UpdateGroupSchema = {
    title: string | null;
};

export type UpdatePersonalChatSchema = {
    title?: string | null;
};

export type UpdateRoleGroupSchema = {
    title?: string | null;
};

export type UserCreate = {
    email: string;
    password: string;
    is_active?: boolean | null;
    is_superuser?: boolean | null;
    is_verified?: boolean | null;
};

export type UserRead = {
    id: string;
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    is_verified?: boolean;
};

export type UserUpdate = {
    password?: string | null;
    email?: string | null;
    is_active?: boolean | null;
    is_superuser?: boolean | null;
    is_verified?: boolean | null;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type GetApiUsersAvatarByGroupUuidData = {
    groupUuid: string;
};

export type GetApiUsersAvatarByGroupUuidResponse = unknown;

export type PostApiUsersAvatarByGroupUuidData = {
    formData: Body_upload_avatar_api_users_avatar__group_uuid__post;
    groupUuid: string;
};

export type PostApiUsersAvatarByGroupUuidResponse = unknown;

export type GetApiUsersMeResponse = UserRead;

export type PatchApiUsersMeData = {
    requestBody: UserUpdate;
};

export type PatchApiUsersMeResponse = UserRead;

export type GetApiUsersByIdData = {
    id: string;
};

export type GetApiUsersByIdResponse = UserRead;

export type PatchApiUsersByIdData = {
    id: string;
    requestBody: UserUpdate;
};

export type PatchApiUsersByIdResponse = UserRead;

export type DeleteApiUsersByIdData = {
    id: string;
};

export type DeleteApiUsersByIdResponse = void;

export type PostApiAuthJwtLoginData = {
    formData: Body_auth_jwt_login_api_auth_jwt_login_post;
};

export type PostApiAuthJwtLoginResponse = BearerResponse;

export type PostApiAuthJwtLogoutResponse = unknown;

export type PostApiAuthRegisterData = {
    requestBody: UserCreate;
};

export type PostApiAuthRegisterResponse = UserRead;

export type PostApiAuthForgotPasswordData = {
    requestBody: Body_reset_forgot_password_api_auth_forgot_password_post;
};

export type PostApiAuthForgotPasswordResponse = unknown;

export type PostApiAuthResetPasswordData = {
    requestBody: Body_reset_reset_password_api_auth_reset_password_post;
};

export type PostApiAuthResetPasswordResponse = unknown;

export type PostApiAuthRequestVerifyTokenData = {
    requestBody: Body_verify_request_token_api_auth_request_verify_token_post;
};

export type PostApiAuthRequestVerifyTokenResponse = unknown;

export type PostApiAuthVerifyData = {
    requestBody: Body_verify_verify_api_auth_verify_post;
};

export type PostApiAuthVerifyResponse = UserRead;

export type GetApiAuthenticatedRouteResponse = unknown;

export type GetApiResponse = unknown;

export type GetApiGroupsAvatarByGroupUuidData = {
    groupUuid: string;
};

export type GetApiGroupsAvatarByGroupUuidResponse = unknown;

export type PostApiGroupsAvatarByGroupUuidData = {
    formData: Body_upload_avatar_api_groups_avatar__group_uuid__post;
    groupUuid: string;
};

export type PostApiGroupsAvatarByGroupUuidResponse = unknown;

export type GetApiGroupsPanoramaByGroupUuidData = {
    groupUuid: string;
};

export type GetApiGroupsPanoramaByGroupUuidResponse = unknown;

export type PostApiGroupsPanoramaByGroupUuidData = {
    formData: Body_upload_panorama_api_groups_panorama__group_uuid__post;
    groupUuid: string;
};

export type PostApiGroupsPanoramaByGroupUuidResponse = unknown;

export type GetApiGroupsByGroupUuidData = {
    groupUuid: string;
};

export type GetApiGroupsByGroupUuidResponse = ReadGroupSchema;

export type PatchApiGroupsByGroupUuidData = {
    groupUuid: string;
    requestBody: UpdateGroupSchema;
};

export type PatchApiGroupsByGroupUuidResponse = unknown;

export type DeleteApiGroupsByGroupUuidData = {
    groupUuid: string;
};

export type DeleteApiGroupsByGroupUuidResponse = unknown;

export type PostApiGroupsData = {
    requestBody: CreateGroupSchema;
};

export type PostApiGroupsResponse = unknown;

export type GetApiPersonalChatsByPersonalChatUuidData = {
    personalChatUuid: string;
};

export type GetApiPersonalChatsByPersonalChatUuidResponse = ReadPersonalChatSchema;

export type PatchApiPersonalChatsByPersonalChatUuidData = {
    personalChatUuid: string;
    requestBody: UpdatePersonalChatSchema;
};

export type PatchApiPersonalChatsByPersonalChatUuidResponse = unknown;

export type DeleteApiPersonalChatsByPersonalChatUuidData = {
    personalChatUuid: string;
};

export type DeleteApiPersonalChatsByPersonalChatUuidResponse = unknown;

export type PostApiPersonalChatsData = {
    requestBody: CreatePersonalChatSchema;
};

export type PostApiPersonalChatsResponse = unknown;

export type GetApiChatsByChatUuidData = {
    chatUuid: string;
};

export type GetApiChatsByChatUuidResponse = ReadChatSchema;

export type PatchApiChatsByChatUuidData = {
    chatUuid: string;
    requestBody: UpdateChatSchema;
};

export type PatchApiChatsByChatUuidResponse = unknown;

export type DeleteApiChatsByChatUuidData = {
    chatUuid: string;
};

export type DeleteApiChatsByChatUuidResponse = unknown;

export type PostApiChatsData = {
    requestBody: CreateChatSchema;
};

export type PostApiChatsResponse = unknown;

export type GetApiRolesGroupByRoleGroupIdData = {
    roleGroupId: number;
};

export type GetApiRolesGroupByRoleGroupIdResponse = ReadRoleGroupSchema;

export type PatchApiRolesGroupByRoleGroupIdData = {
    requestBody: UpdateRoleGroupSchema;
    roleGroupId: number;
};

export type PatchApiRolesGroupByRoleGroupIdResponse = unknown;

export type DeleteApiRolesGroupByRoleGroupIdData = {
    roleGroupId: number;
};

export type DeleteApiRolesGroupByRoleGroupIdResponse = unknown;

export type PostApiRolesGroupData = {
    requestBody: CreateRoleGroupSchema;
};

export type PostApiRolesGroupResponse = unknown;

export type $OpenApiTs = {
    '/api/users/avatar/{group_uuid}': {
        get: {
            req: GetApiUsersAvatarByGroupUuidData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        post: {
            req: PostApiUsersAvatarByGroupUuidData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/users/me': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: UserRead;
                /**
                 * Missing token or inactive user.
                 */
                401: unknown;
            };
        };
        patch: {
            req: PatchApiUsersMeData;
            res: {
                /**
                 * Successful Response
                 */
                200: UserRead;
                /**
                 * Bad Request
                 */
                400: ErrorModel;
                /**
                 * Missing token or inactive user.
                 */
                401: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/users/{id}': {
        get: {
            req: GetApiUsersByIdData;
            res: {
                /**
                 * Successful Response
                 */
                200: UserRead;
                /**
                 * Missing token or inactive user.
                 */
                401: unknown;
                /**
                 * Not a superuser.
                 */
                403: unknown;
                /**
                 * The user does not exist.
                 */
                404: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        patch: {
            req: PatchApiUsersByIdData;
            res: {
                /**
                 * Successful Response
                 */
                200: UserRead;
                /**
                 * Bad Request
                 */
                400: ErrorModel;
                /**
                 * Missing token or inactive user.
                 */
                401: unknown;
                /**
                 * Not a superuser.
                 */
                403: unknown;
                /**
                 * The user does not exist.
                 */
                404: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        delete: {
            req: DeleteApiUsersByIdData;
            res: {
                /**
                 * Successful Response
                 */
                204: void;
                /**
                 * Missing token or inactive user.
                 */
                401: unknown;
                /**
                 * Not a superuser.
                 */
                403: unknown;
                /**
                 * The user does not exist.
                 */
                404: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/auth/jwt/login': {
        post: {
            req: PostApiAuthJwtLoginData;
            res: {
                /**
                 * Successful Response
                 */
                200: BearerResponse;
                /**
                 * Bad Request
                 */
                400: ErrorModel;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/auth/jwt/logout': {
        post: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Missing token or inactive user.
                 */
                401: unknown;
            };
        };
    };
    '/api/auth/register': {
        post: {
            req: PostApiAuthRegisterData;
            res: {
                /**
                 * Successful Response
                 */
                201: UserRead;
                /**
                 * Bad Request
                 */
                400: ErrorModel;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/auth/forgot-password': {
        post: {
            req: PostApiAuthForgotPasswordData;
            res: {
                /**
                 * Successful Response
                 */
                202: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/auth/reset-password': {
        post: {
            req: PostApiAuthResetPasswordData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Bad Request
                 */
                400: ErrorModel;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/auth/request-verify-token': {
        post: {
            req: PostApiAuthRequestVerifyTokenData;
            res: {
                /**
                 * Successful Response
                 */
                202: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/auth/verify': {
        post: {
            req: PostApiAuthVerifyData;
            res: {
                /**
                 * Successful Response
                 */
                200: UserRead;
                /**
                 * Bad Request
                 */
                400: ErrorModel;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/authenticated-route': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
    };
    '/api': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
    };
    '/api/groups/avatar/{group_uuid}': {
        get: {
            req: GetApiGroupsAvatarByGroupUuidData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        post: {
            req: PostApiGroupsAvatarByGroupUuidData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/groups/panorama/{group_uuid}': {
        get: {
            req: GetApiGroupsPanoramaByGroupUuidData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        post: {
            req: PostApiGroupsPanoramaByGroupUuidData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/groups/{group_uuid}': {
        get: {
            req: GetApiGroupsByGroupUuidData;
            res: {
                /**
                 * Successful Response
                 */
                200: ReadGroupSchema;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        patch: {
            req: PatchApiGroupsByGroupUuidData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        delete: {
            req: DeleteApiGroupsByGroupUuidData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/groups/': {
        post: {
            req: PostApiGroupsData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/personal_chats/{personal_chat_uuid}': {
        get: {
            req: GetApiPersonalChatsByPersonalChatUuidData;
            res: {
                /**
                 * Successful Response
                 */
                200: ReadPersonalChatSchema;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        patch: {
            req: PatchApiPersonalChatsByPersonalChatUuidData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        delete: {
            req: DeleteApiPersonalChatsByPersonalChatUuidData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/personal_chats/': {
        post: {
            req: PostApiPersonalChatsData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/chats/{chat_uuid}': {
        get: {
            req: GetApiChatsByChatUuidData;
            res: {
                /**
                 * Successful Response
                 */
                200: ReadChatSchema;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        patch: {
            req: PatchApiChatsByChatUuidData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        delete: {
            req: DeleteApiChatsByChatUuidData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/chats/': {
        post: {
            req: PostApiChatsData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/roles_group/{role_group_id}': {
        get: {
            req: GetApiRolesGroupByRoleGroupIdData;
            res: {
                /**
                 * Successful Response
                 */
                200: ReadRoleGroupSchema;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        patch: {
            req: PatchApiRolesGroupByRoleGroupIdData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        delete: {
            req: DeleteApiRolesGroupByRoleGroupIdData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/roles_group/': {
        post: {
            req: PostApiRolesGroupData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
};